### ISSUE TITLE
Use the new compression tool to generate optimized models

### ISSUE THREAD

**Issue by EmileRolley** [datagir/nosgestesclimat#1661]
> Repository of the new tool: https://github.com/EmileRolley/publiopti

Following up https://github.com/datagir/nosgestesclimat-site/issues/746

## Tasks

* [x] Integrate the compression tool in the `rulesToJSON` script
* [x] Generate compressed models for each supported languages
* [x] Fix the Netlify deploy errors with the Node version
* [x] Investigate the differences of number of rules between the french model and its english translation.
* [x] Need to have complete rules for the "services sociétaux" graph
* [x] Fix the optimisation of the "Services sociétaux": `émissions hors direct ménages par hab` could be optimized?
* [x] Handle "empty rules with no parents"
* [x] Add a minimal documentation in publiopti
